AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon EKS Cluster with Fargate Profile'

Parameters:

  ClusterName:
    Type: String
    Default: my-eks-cluster
    Description: Name of the EKS cluster.

Resources:

  MyEKS:
    Type: 'AWS::EKS::Cluster'
    Properties:
      Name: !Ref ClusterName
      Version: '1.21'  # Use the desired EKS version
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !GetAtt [FargateSecurityGroup, GroupId]
        SubnetIds:
          - !Ref PublicSubnet1
          - !Ref PublicSubnet2
        EndpointPublicAccess: true
        EndpointPrivateAccess: true

  FargateSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security group for EKS Fargate
      VpcId: !Ref MyVPC

  FargateProfile:
    Type: 'AWS::EKS::FargateProfile'
    Properties:
      ClusterName: !Ref MyEKS
      FargateProfileName: 'default'  # Name of the Fargate profile
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2

Outputs:

  EKSClusterName:
    Description: EKS Cluster Name
    Value: !Ref MyEKS
